### ISSUE TITLE
Patch for /trunk/cs/csparse.c

### ISSUE THREAD

**Issue by GoogleCodeExporter** [blong42/clearsilver#11]
```
Memory leak in include_parse(). Added missing deallocations of arg1 members. 
Removed redundant initialization (arg1.argexpr = NULL).
```

Original issue reported on code.google.com by `dj5qv...@gmail.com` on 8 Aug 2013 at 12:52

**Comment by blong42** [comment]
Thanks for the patch, this was fixed in https://github.com/blong42/clearsilver/commit/1e19f629924b53e788af80773ce559680453efac
