### ISSUE TITLE
clearsilver 0.11.0  -- multiple instances of non-standard path "/neo/opt" in released source code

### ISSUE THREAD

**Issue by Corin-EU** [blong42/clearsilver#15]
In the recently released tar.gz archive file for clearsilver 0.11.0, there are numerous instances of the path "/neo/opt" in the source code.  It iseven being used as the path to the python interpreter (the "shebang" line) in numerous python scripts.

       ./cdbi/log.py:#!/neo/opt/bin/python
       ./cdbi/odb.py:#!/neo/opt/bin/python
       ./configure.in:    csharp_search_path="/neo/opt /usr/local /usr"
       ./configure.in:    java_search_path="/neo/opt /usr/local /usr /usr/lib"
       ./configure.in:  CPPFLAGS="$CPPFLAGS -I/neo/opt/include"
       ./configure.in:  LDFLAGS="$LDFLAGS -L/neo/opt/lib"
       ./configure.in:  apache_search_path="$cs_cv_apache_path /neo/opt /usr/local /usr"
       ./configure.in:  perl_search_path="/neo/opt /usr/local /usr"
       ./configure.in:  python_search_path="/neo/opt /usr/local /usr /c"
       ./configure.in:  ruby_search_path="/neo/opt /usr/local /usr"
       ./configure.in:if test -d /neo/opt/include; then
       ./python/examples/base/CSPage.py:#!/neo/opt/bin/python
       ./python/examples/base/hdfhelp.py:#!/neo/opt/bin/python
       ./python/examples/base/log.py:#!/neo/opt/bin/python
       ./python/examples/trans/trans.py:#!/neo/opt/bin/python
       ./scripts/ChangeLog.py:#!/neo/opt/bin/python
       ./scripts/cs_lint.py:#!/neo/opt/bin/python
 
As /neo/opt is most definitely not a standard linux directory (not LSB), presumably this is a path specific to the development environment of clearsilver and should therefore not be present in the released code, especially not as the path to the python interpreter ("shebang" line) in the various python scripts where it is present.

**Comment by blong42** [comment]
sure, done
