### ISSUE TITLE
clearsilver's website is down!

### ISSUE THREAD

**Issue by darklie** [blong42/clearsilver#20]

**Comment by blong42** [comment]
Yeah, the 20y old server finally gave up the ghost... and I was sure I'd set up rsync backups at one point, but can't find the destination... it may have been a box that was removed years ago.

I'm currently rebuilding from the internet archive.

The docs were copied to the wiki here on github several years ago, and all of the downloads should be on here as well.  If something is missing, let me know and I can probably fix that quicker than I'll get the website back up.

**Comment by blong42** [comment]
Forgot to update this, the site has been back up since a couple days after my last update in late Jan.
